name: stock-analyzer
services:
- name: backend
  github:
    repo: YOUR_GITHUB_USERNAME/stockimageanalyzer
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt
  dockerfile_path: Dockerfile
  http_port: 8000
  source_dir: backend
  envs:
  - key: ENVIRONMENT
    value: production
  - key: CORS_ORIGINS
    value: https://yourdomain.com,https://www.yourdomain.com
  health_check:
    http_path: /

- name: frontend
  github:
    repo: YOUR_GITHUB_USERNAME/stockimageanalyzer
    branch: main
    deploy_on_push: true
  build_command: npm install && npm run build
  dockerfile_path: Dockerfile
  source_dir: frontend
  http_port: 3000
  envs:
  - key: REACT_APP_API_URL
    value: https://api.yourdomain.com

static_sites:
- source_dir: frontend/build
  routes:
  - path: /

domains:
- name: yourdomain.com
- name: www.yourdomain.com
