apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stock-analyzer-api
  labels:
    app: stock-analyzer
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/stock-analyzer-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
